---
- name: Deploy Docker image to Azure VM
  hosts: azure_vm
  become: yes
  tasks:
    - name: Copy Docker image to Azure VM
      copy:
        src: ./Install_App_VM_Ansible/automation_app.tar              # Path to image on your local machine
        dest: /home/azureadmin/automation_app.tar
        mode: 0644

    - name: Load Docker image on Azure VM
      ansible.builtin.shell: |
        ls
        pwd
        sudo docker load -i /home/azureadmin/automation_app.tar
      args:
        creates: /home/azureadmin/automation_app.tar

    - name: Run Docker container from loaded image
      ansible.builtin.shell: |
        sudo docker run -d -p 80:80 automation_app
      args:
        creates: /var/run/docker.sock  # Only runs if Docker is installed

    - name: Confirm Docker container is running
      ansible.builtin.shell: docker ps
      register: docker_ps_output

    - name: Display running Docker containers
      debug:
        msg: "{{ docker_ps_output.stdout }}"
        
    - name: Remove Docker image file after loading
      ansible.builtin.file:
        path: /home/azureadmin/automation_app.tar
        state: absent
