---
- name: Deploy Docker image to Azure VM
  hosts: azure_vm
  become: yes
  tasks:
    - name: Copy the .tar file to the remote server
      copy:
        src: /automation_app.tar  # Relative path to the .tar file in the 'test' folder
        dest: /home/azureadmin/automation_app.tar  # Destination path on the remote server
        mode: '0644'  # Permissions for the remote file (optional)


    - name: Load Docker image on Azure VM
      ansible.builtin.shell: |
        sudo docker load -i /home/azureadmin/automation_app.tar
      args:
        creates: /home/azureadmin/automation_app.tar

    - name: Run Docker container from loaded image
      ansible.builtin.docker_container:
        name: automation_app
        image: automation_app:latest
        state: started
        published_ports:
          - "80:80"

    - name: Confirm Docker container is running
      ansible.builtin.shell: docker ps
      register: docker_ps_output

    - name: Display running Docker containers
      debug:
        msg: "{{ docker_ps_output.stdout }}"
        
    - name: Remove Docker image file after loading
      ansible.builtin.file:
        path: /home/azureadmin/automation_app.tar
        state: absent
